
export const sectionOne = {
    id: 'ingredients',
    lightBg: true,
    lightHeaderLine: true,
    lightTextDesc: false, 
    infoHeader: "vegan soap handmade with love",
    subHeader1: '',
    infoParagraph1: "Soap is a salt of a fatty acid[1] used in a variety of cleansing and lubricating products. In a domestic setting, soaps are surfactants usually used for washing, bathing, and other types of housekeeping. In industrial settings, soaps are used as thickeners, components of some lubricants, and precursors to catalysts.",
    infoParagraph2: "When used for cleaning, soap solubilizes particles and grime, which can then be separated from the article being cleaned. In hand washing, as a surfactant, when lathered with a little water, soap kills microorganisms by disorganizing their membrane lipid bilayer and denaturing their proteins. It also emulsifies oils, enabling them to be carried away by running water.",
    imgStart: false,
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: true,
    detailImg1: require('../../images/klean-2.png').default,
    detailHeader1: "vegan ingredients",
    detailText1: 'Soap is created by mixing fats and oils with a base, as opposed to detergent which is created by combining chemical compounds in a mixer.',
    detailImg2: require('../../images/klean-2.png').default,
    detailHeader2: "biodegradable packaging",
    detailText2: 'Veganism is the practice of abstaining from the use of animal products, particularly in diet, and an associated philosophy that rejects the commodity status of animals. An individual who follows the diet or philosophy is known as a vegan.',
    detailImg3: require('../../images/klean-2.png').default,
    detailHeader3: "giving back",
    detailText3: 'Packaging is the science, art and technology of enclosing or protecting products for distribution, storage, sale, and use. Packaging also refers to the process of designing, evaluating, and producing packages. '
}
export const sectionTwo = {
    id: 'shop',
    lightBg: false,
    lightText: false,
    lightTextDesc: true, 
    infoHeader: "shop our soap",
    subHeader1: '',
    infoParagraph1: "COMING SOON...",
    infoParagraph2:"subscribe for our newsletter to stay up-to-date!" ,
    imgStart: false,
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: true,
    detailImg1: require('../../images/klean-2.png').default,
    detailHeader1: "vegan ingredients",
    detailText1: 'Soap is created by mixing fats and oils with a base, as opposed to detergent which is created by combining chemical compounds in a mixer.',
    detailImg2: require('../../images/klean-2.png').default,
    detailHeader2: "biodegradable packaging",
    detailText2: 'Veganism is the practice of abstaining from the use of animal products, particularly in diet, and an associated philosophy that rejects the commodity status of animals. An individual who follows the diet or philosophy is known as a vegan.',
    detailImg3: require('../../images/klean-2.png').default,
    detailHeader3: "giving back",
    detailText3: 'Packaging is the science, art and technology of enclosing or protecting products for distribution, storage, sale, and use. Packaging also refers to the process of designing, evaluating, and producing packages. '
}